<a href="https://colab.research.google.com/github/Kalana-Lakshan/ML-Self-Learning/blob/main/ML_Hackathon_practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import LabelEncoder

In [25]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

In [26]:
train_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [27]:
num_cols_train = train_data.select_dtypes(include = np.number).columns
cat_cols_train = train_data.select_dtypes(include = 'object').columns

In [28]:
num_cols_test= test_data.select_dtypes(include = np.number).columns
cat_cols_test= test_data.select_dtypes(include = 'object').columns

In [29]:
train_data[num_cols_train] = train_data[num_cols_train].fillna(train_data[num_cols_train].median())
train_data[cat_cols_train] = train_data[cat_cols_train].fillna('unknown')

In [30]:
test_data[num_cols_test] = test_data[num_cols_test].fillna(test_data[num_cols_test].median())
test_data[cat_cols_test] = test_data[cat_cols_test].fillna('unknown')

In [31]:
encoder = LabelEncoder()

In [32]:
num_cols_test == num_cols_train

array([ True,  True,  True,  True,  True,  True])

In [33]:
cat_cols_test == cat_cols_train

array([ True,  True,  True,  True,  True,  True,  True])

In [34]:
for col in cat_cols_train:
  train_data[col] = encoder.fit_transform(train_data[col].astype(str))
  test_data[col] = encoder.fit_transform(test_data[col].astype(str))

In [35]:
X = train_data.drop(train_data.columns[-1],axis = 1)
y = train_data[train_data.columns[-1]]

In [36]:
model = XGBClassifier(
    n_estimators = 200,
    max_depth = 5,
    learning_rate = 0.1,
    random_state = 42
)

In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [38]:
y_predict = model.predict(X_test)
print("Accuracy",accuracy_score(y_predict,y_test))

Accuracy 0.7924094307073031

In [39]:
print(confusion_matrix(y_predict,y_test))

[[665 165]
 [196 713]]

In [40]:
print(classification_report(y_predict,y_test))

              precision    recall  f1-score   support

           0       0.77      0.80      0.79       830
           1       0.81      0.78      0.80       909

    accuracy                           0.79      1739
   macro avg       0.79      0.79      0.79      1739
weighted avg       0.79      0.79      0.79      1739

In [41]:
test_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0,0,1,2784,2,27.0,0,0.0,0.0,0.0,0.0,0.0,2912
1,1,0,0,1867,2,19.0,0,0.0,9.0,0.0,2823.0,0.0,2406
2,2,1,1,257,0,31.0,0,0.0,0.0,0.0,0.0,0.0,3376
3,3,1,0,259,2,38.0,0,0.0,6652.0,0.0,181.0,585.0,2711
4,4,0,0,1940,2,20.0,0,10.0,0.0,635.0,0.0,0.0,668

In [42]:
train_data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0,1,0,149,2,39.0,0,0.0,0.0,0.0,0.0,0.0,5252,False
1,1,0,0,2184,2,24.0,0,109.0,9.0,25.0,549.0,44.0,4502,True
2,2,1,0,1,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,457,False
3,3,1,0,1,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,7149,False
4,4,0,0,2186,2,16.0,0,303.0,70.0,151.0,565.0,2.0,8319,True

In [45]:
test_predict = model.predict(test_data)

In [48]:
output = pd.DataFrame({"PassengerId":test_data["PassengerId"],"Transported":model.predict(test_data)})

In [49]:
output.to_csv("submission.csv")