<a href="https://colab.research.google.com/github/Kalana-Lakshan/ML-Self-Learning/blob/main/Predicting_Heart_Disease_Playground_Series_Season_6_Episode_2_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd

In [28]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
sample_submission_data = pd.read_csv('sample_submission.csv')

In [29]:
train_data.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [30]:
train_data.describe()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,54.136706,0.714735,3.312752,130.497433,245.011814,0.079987,0.981660,152.816763,0.273725,0.716028,1.455871,0.451040,4.618873
std,181865.479132,8.256301,0.451541,0.851615,14.975802,33.681581,0.271274,0.998783,19.112927,0.445870,0.948472,0.545192,0.798549,1.950007
min,0.000000,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000
25%,157499.750000,48.000000,0.000000,3.000000,120.000000,223.000000,0.000000,0.000000,142.000000,0.000000,0.000000,1.000000,0.000000,3.000000
50%,314999.500000,54.000000,1.000000,4.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.100000,1.000000,0.000000,3.000000
75%,472499.250000,60.000000,1.000000,4.000000,140.000000,269.000000,0.000000,2.000000,166.000000,1.000000,1.400000,2.000000,1.000000,7.000000
max,629999.000000,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000

In [31]:
test_data.describe()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.000000,270000.00000,270000.000000
mean,764999.500000,54.159870,0.716315,3.315107,130.555089,245.045270,0.080052,0.978493,152.783756,0.274656,0.718082,1.459356,0.45480,4.619774
std,77942.430678,8.255471,0.450787,0.851762,15.007908,33.695458,0.271374,0.998686,19.153454,0.446341,0.947417,0.546186,0.80127,1.950273
min,630000.000000,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.00000,3.000000
25%,697499.750000,48.000000,0.000000,3.000000,120.000000,223.000000,0.000000,0.000000,142.000000,0.000000,0.000000,1.000000,0.00000,3.000000
50%,764999.500000,54.000000,1.000000,4.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.100000,1.000000,0.00000,3.000000
75%,832499.250000,60.000000,1.000000,4.000000,140.000000,269.000000,0.000000,2.000000,166.000000,1.000000,1.400000,2.000000,1.00000,7.000000
max,899999.000000,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.00000,7.000000

In [32]:
sample_submission_data.describe()

                  id  Heart Disease
count  270000.000000       270000.0
mean   764999.500000            0.0
std     77942.430678            0.0
min    630000.000000            0.0
25%    697499.750000            0.0
50%    764999.500000            0.0
75%    832499.250000            0.0
max    899999.000000            0.0

In [33]:
features = train_data.columns.tolist()
features

['id',
 'Age',
 'Sex',
 'Chest pain type',
 'BP',
 'Cholesterol',
 'FBS over 120',
 'EKG results',
 'Max HR',
 'Exercise angina',
 'ST depression',
 'Slope of ST',
 'Number of vessels fluro',
 'Thallium',
 'Heart Disease']

In [34]:
features = features[1:-1]
features

['Age',
 'Sex',
 'Chest pain type',
 'BP',
 'Cholesterol',
 'FBS over 120',
 'EKG results',
 'Max HR',
 'Exercise angina',
 'ST depression',
 'Slope of ST',
 'Number of vessels fluro',
 'Thallium']

In [35]:
len(features)

13

In [36]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

features_to_encode = ['Chest pain type','EKG results','Slope of ST','Thallium']

train_data_to_encode = train_data[features_to_encode].copy()

for column in features_to_encode:
  if train_data_to_encode[column].isnull().any():
    mode_value = train_data_to_encode[column].mode()[0]
    train_data_to_encode[column].fillna(mode_value,inplace = True)

ordinalencoder = OrdinalEncoder()
train_data_to_encode[features_to_encode] = ordinalencoder.fit_transform(train_data_to_encode[features_to_encode])

train_data[features_to_encode] = train_data_to_encode[features_to_encode]

In [37]:
test_data_to_encode = test_data[features_to_encode].copy()

for column in features_to_encode:
  if test_data_to_encode[column].isnull().any():
    mode_value = test_data_to_encode[column].mode()[0]
    test_data_to_encode[column].fillna(mode_value,inplace = True)

test_data[features_to_encode] = ordinalencoder.fit_transform(test_data_to_encode[features_to_encode])

In [38]:
train_data.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,3.0,152,239,0,0.0,158,1,3.6,1.0,2,2.0,Presence
1,1,52,1,0.0,125,325,0,2.0,171,0,0.0,0.0,0,0.0,Absence
2,2,56,0,1.0,160,188,0,2.0,151,0,0.0,0.0,0,0.0,Absence
3,3,44,0,2.0,134,229,0,2.0,150,0,1.0,1.0,0,0.0,Absence
4,4,58,1,3.0,140,234,0,2.0,125,1,3.8,1.0,3,0.0,Presence

In [39]:
train_data.describe()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,54.136706,0.714735,2.312752,130.497433,245.011814,0.079987,0.981660,152.816763,0.273725,0.716028,0.455871,0.451040,0.800733
std,181865.479132,8.256301,0.451541,0.851615,14.975802,33.681581,0.271274,0.998783,19.112927,0.445870,0.948472,0.545192,0.798549,0.971024
min,0.000000,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,157499.750000,48.000000,0.000000,2.000000,120.000000,223.000000,0.000000,0.000000,142.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,314999.500000,54.000000,1.000000,3.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.100000,0.000000,0.000000,0.000000
75%,472499.250000,60.000000,1.000000,3.000000,140.000000,269.000000,0.000000,2.000000,166.000000,1.000000,1.400000,1.000000,1.000000,2.000000
max,629999.000000,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,3.000000,2.000000

In [41]:
from sklearn.model_selection import train_test_split

X_full = train_data[features]
y_full = train_data['Heart Disease'].map({'Absence':0,'Presence':1})

fully_imputed_data = X_full.copy()
fully_imputed_data['target'] = y_full
fully_imputed_data.dropna(subset = ['target'],inplace = True)

X_full_final = fully_imputed_data[features]
y_full_final = fully_imputed_data['target']
X_train,X_val,y_train,y_val = train_test_split(X_full_final,y_full_final,test_size = 0.2,random_state = 42)

import xgboost as xgb

xgmodel = xgb.XGBClassifier(random_state = 42)
xgmodel.fit(X_train,y_train)

from sklearn.metrics import roc_auc_score

y_predict_probabilities = xgmodel.predict_proba(X_val)[:,1]

auc_roc_value = roc_auc_score(y_val,y_predict_probabilities)

In [44]:
auc_roc_value

np.float64(0.9546865164774129)

In [46]:
predictions = xgmodel.predict_proba(test_data[features])[:,1]

predictions

array([0.9555155 , 0.00752217, 0.9859125 , ..., 0.04705456, 0.14831823,
       0.02623646], dtype=float32)

In [47]:
pd.DataFrame({'id':test_data['id'],'Heart Disease': predictions}).to_csv("Submission1.csv")