<a href="https://colab.research.google.com/github/Kalana-Lakshan/ML-Self-Learning/blob/main/Predicting_Heart_Disease_Playground_Series_Season_6_Episode_2_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
sample_submission_data = pd.read_csv('sample_submission.csv')

In [3]:
train_data.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [4]:
train_data.describe()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000
mean,10715.500000,54.218412,0.716079,3.312617,130.550625,245.254293,0.081467,0.986655,152.866181,0.274496,0.711521,1.459360,0.457960,4.610302
std,6187.029821,8.277462,0.450910,0.853494,15.032168,33.579255,0.273557,0.998954,19.273538,0.446270,0.939520,0.546157,0.807035,1.949256
min,0.000000,29.000000,0.000000,1.000000,94.000000,149.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000
25%,5357.750000,48.000000,0.000000,3.000000,120.000000,223.000000,0.000000,0.000000,142.000000,0.000000,0.000000,1.000000,0.000000,3.000000
50%,10715.500000,54.000000,1.000000,4.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.000000,1.000000,0.000000,3.000000
75%,16073.250000,60.000000,1.000000,4.000000,140.000000,269.000000,0.000000,2.000000,167.000000,1.000000,1.400000,2.000000,1.000000,7.000000
max,21431.000000,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000

In [5]:
test_data.describe()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,24970.000000,24970.000000,24970.000000,24970.000000,24970.000000,24970.000000,24970.000000,24970.000000,24970.000000,24969.000000,24969.000000,24969.000000,24969.000000,24969.000000
mean,642484.500000,54.089748,0.712415,3.306087,130.645855,244.907369,0.080817,0.977213,153.033240,0.268893,0.718010,1.454524,0.453162,4.610717
std,7208.362447,8.229195,0.452646,0.858287,15.073974,33.688492,0.272559,0.998778,19.122318,0.443393,0.949465,0.546266,0.801499,1.948576
min,630000.000000,29.000000,0.000000,1.000000,94.000000,149.000000,0.000000,0.000000,14.000000,0.000000,0.000000,1.000000,0.000000,3.000000
25%,636242.250000,48.000000,0.000000,3.000000,120.000000,222.000000,0.000000,0.000000,142.000000,0.000000,0.000000,1.000000,0.000000,3.000000
50%,642484.500000,54.000000,1.000000,4.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.100000,1.000000,0.000000,3.000000
75%,648726.750000,60.000000,1.000000,4.000000,140.000000,269.000000,0.000000,2.000000,168.000000,1.000000,1.400000,2.000000,1.000000,7.000000
max,654969.000000,77.000000,1.000000,4.000000,200.000000,417.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000

In [6]:
sample_submission_data.describe()

                  id  Heart Disease
count  233015.000000       233015.0
mean   746507.000000            0.0
std     67265.780825            0.0
min    630000.000000            0.0
25%    688253.500000            0.0
50%    746507.000000            0.0
75%    804760.500000            0.0
max    863014.000000            0.0

In [7]:
features = train_data.columns.tolist()
features

['id',
 'Age',
 'Sex',
 'Chest pain type',
 'BP',
 'Cholesterol',
 'FBS over 120',
 'EKG results',
 'Max HR',
 'Exercise angina',
 'ST depression',
 'Slope of ST',
 'Number of vessels fluro',
 'Thallium',
 'Heart Disease']

In [8]:
features = features[1:-1]
features

['Age',
 'Sex',
 'Chest pain type',
 'BP',
 'Cholesterol',
 'FBS over 120',
 'EKG results',
 'Max HR',
 'Exercise angina',
 'ST depression',
 'Slope of ST',
 'Number of vessels fluro',
 'Thallium']

In [9]:
len(features)

13

In [14]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

features_to_encode = ['Chest pain type','EKG results','Slope of ST','Thallium']

train_data_to_encode = train_data[features_to_encode].copy()

for column in features_to_encode:
  if train_data_to_encode[column].isnull().any():
    mode_value = train_data_to_encode[column].mode()[0]
    train_data_to_encode[column].fillna(mode_value,inplace = True)

ordinalencoder = OrdinalEncoder()
train_data_to_encode[features_to_encode] = ordinalencoder.fit_transform(train_data_to_encode[features_to_encode])

train_data[features_to_encode] = train_data_to_encode[features_to_encode]

In [16]:
test_data_to_encode = test_data[features_to_encode].copy()

for column in features_to_encode:
  if test_data_to_encode[column].isnull().any():
    mode_value = test_data_to_encode[column].mode()[0]
    test_data_to_encode[column].fillna(mode_value,inplace = True)

test_data[features_to_encode] = ordinalencoder.fit_transform(test_data_to_encode[features_to_encode])

In [17]:
train_data.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,3.0,152,239,0,0.0,158,1,3.6,1.0,2,2.0,Presence
1,1,52,1,0.0,125,325,0,2.0,171,0,0.0,0.0,0,0.0,Absence
2,2,56,0,1.0,160,188,0,2.0,151,0,0.0,0.0,0,0.0,Absence
3,3,44,0,2.0,134,229,0,2.0,150,0,1.0,1.0,0,0.0,Absence
4,4,58,1,3.0,140,234,0,2.0,125,1,3.8,1.0,3,0.0,Presence

In [19]:
train_data.describe()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000,21432.000000
mean,10715.500000,54.218412,0.716079,2.312617,130.550625,245.254293,0.081467,0.986655,152.866181,0.274496,0.711521,0.459360,0.457960,0.797032
std,6187.029821,8.277462,0.450910,0.853494,15.032168,33.579255,0.273557,0.998954,19.273538,0.446270,0.939520,0.546157,0.807035,0.970881
min,0.000000,29.000000,0.000000,0.000000,94.000000,149.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5357.750000,48.000000,0.000000,2.000000,120.000000,223.000000,0.000000,0.000000,142.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10715.500000,54.000000,1.000000,3.000000,130.000000,243.000000,0.000000,0.000000,157.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,16073.250000,60.000000,1.000000,3.000000,140.000000,269.000000,0.000000,2.000000,167.000000,1.000000,1.400000,1.000000,1.000000,2.000000
max,21431.000000,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,3.000000,2.000000

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_val,y_train,y_val = train_test_split(train_data[features],train_data['Heart Disease'],test_size = 0.2,random_state = 42)

import xgboost as xgb

xgmodel = xgb.XGBClassifier(random_state = 42)
xgmodel.fit(X_train,y_train)

from sklearn.metrics import roc_auc_score

y_predict_probabilities = xgmodel.predict_proba(X_val)[:,1]

auc_roc_value = roc_auc_score(y_val,y_predict_probabilities)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got ['A' 'Absence' 'Presence']

In [18]:
from sklearn.model_selection import train_test_split

X_full_train = train_data[features]
y_full_train = train_data['Heart Disease']
X_test = test_data[features]

X_train, X_val, y_train, y_val = train_test_split(X_full_train, y_full_train, test_size=0.2, random_state=42)

In [ ]:
import xgboost as xgb

model = xgb.XGBClassifier(random_state=42)
model.fit(X_train, y_train)

In [ ]:
import xgboost as xgb
from sklearn.metrics import roc_auc_score

model = xgb.XGBClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred_proba = model.predict_proba(X_val)[:, 1] # Get probabilities for the positive class
auc_roc = roc_auc_score(y_val, y_pred_proba)

print(f"AUC-ROC Score on Validation Set: {auc_roc}")